apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/treddy-tenant/my-app/devfile-sample-code-with-quarkus@sha256:72ef15787b6d224c55d9976d7bc5434750bd2379b83c4ab325ff55e9fd02ffb2
        name: my-java-quarkus
        resources: {}
status: {}
